[dev]
  command = 'npm start'
[build]
  command = "npm run production"
  publish = "dist" 
[[plugins]]
  package = "netlify-plugin-inline-critical-css"
[[plugins]]
  package = "netlify-plugin-image-optim"